---
title: "Homework 4"
author: "Greta Savitsky"
date: "2/9/2022"
output: html_document
---
# Question 1
```{r}
x = 1.1
a = 2.2
b = 3.3
```
```{r}
z <- x**(a**b)
print(z)
```
```{r}
z <- (x**a)**b
print(z)
```
```{r}
z <- 3*x**3 + 2*x**2 + 1
print(z)
```
# Question 2
```{r}
a <- c(seq(1:8),rev(seq(1:7)))
print(a)
```
```{r}
b <- c(1, rep(2, 2), rep(3,3), rep(4,4), rep(5,5))
print(b)
```
```{r}
c <- c(5, rep(4, 2), rep(3,3), rep(2,4), rep(1,5))
print(c)
```
# Question 3
```{r}
a <- runif(2)
x <- a[1]
y <- a[2]
```
```{r}
r <-sqrt(x**2+y**2)
theta <- atan(y/x)

b <- c(r,theta)

print(b)
```

# Question 4
```{r}
queue <- c("sheep", "fox", "owl", "ant")
print(queue)
```
```{r}
queue <- append(queue, "serpent")
print(queue)
```
```{r}
queue <- queue[! queue %in% c("sheep")]
print(queue)
```
```{r}
queue <- append(queue, "donkey", after=0)
print(queue)
```
```{r}
queue <- queue[! queue %in% c("serpent")]
print(queue)
```
```{r}
queue <- queue[! queue %in% c("owl")]
print(queue)
```
```{r}
queue <- append(queue, "aphid", after=(match("ant",queue)-1))
print(queue)
```
```{r}
answer <- match("aphid",queue)
```
# Question 5
```{r}
vector <- (seq(from = 1, to = 100, by = 2))

vector <- (vector[!vector%%7==0])

vector <- (vector[!vector%%3==0])

print(vector)

```




