---
title: "Homework_06"
author: "Greta Savitsky"
date: "2/23/2022"
output: html_document
---

#### read in required libraries
```{r}
library(ggplot2) # for graphics
library(MASS) # for maximum likelihood estimation
```

#### read in data from desktop
```{r}
z <- read.csv("~/Desktop/tair850-2010.csv")
sd(complete.cases(z))
z <- z[,2:3]
z$number <- c(1:2400)
str(z)
head(z)
z <- na.omit(z)
summary(z)
```


#### plot histogram
```{r}
p1 <- ggplot(data=z, aes(x=Freq, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2)
print(p1)
```


#### add kernel density plot
```{r}
p1 <-  p1 +  geom_density(linetype="dotted",size=0.75)
print(p1)
```


# Normal distribution
#### fit normal distribution
```{r}
normPars <- fitdistr(z$Freq,"normal")
print(normPars)
str(normPars)
normPars$estimate["mean"] # note structure of getting a named attribute
```


#### probability density for normal dist
```{r}
meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

xval <- seq(0,max(z$Freq),len=length(z$Freq))

stat <- stat_function(aes(x = xval, y = ..y..), fun = dnorm, colour="red", n = length(z$Freq), args = list(mean = meanML, sd = sdML))

length(stat)
 
p1 + stat
```


# Exponential distribution
```{r}
expoPars <- fitdistr(z$Freq,"exponential")
rateML <- expoPars$estimate["rate"]

stat2 <- stat_function(aes(x = xval, y = ..y..), fun = dexp, colour="blue", n = length(z$Freq), args = list(rate=rateML))
 p1 + stat + stat2
```


# Uniform distribution
```{r}
stat3 <- stat_function(aes(x = xval, y = ..y..), fun = dunif, colour="darkgreen", n = length(z$Freq), args = list(min=min(z$Freq), max=max(z$Freq)))
 p1 + stat + stat2 + stat3
```


# Gamma distribution
```{r}
gammaPars <- fitdistr(z$Freq,"gamma")
shapeML <- gammaPars$estimate["shape"]
rateML <- gammaPars$estimate["rate"]

stat4 <- stat_function(aes(x = xval, y = ..y..), fun = dgamma, colour="brown", n = length(z$Freq), args = list(shape=shapeML, rate=rateML))
 p1 + stat + stat2 + stat3 + stat4
```
 

# Beta distribution
```{r}
pSpecial <- ggplot(data=z, aes(x=Freq/(max(Freq + 0.1)), y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) + 
  xlim(c(0,1)) +
  geom_density(size=0.75,linetype="dotted")

betaPars <- fitdistr(x=z$Freq/max(z$Freq +      
  0.1),start=list(shape1=1,shape2=2),"beta")
  shape1ML <- betaPars$estimate["shape1"]
  shape2ML <- betaPars$estimate["shape2"]

statSpecial <- stat_function(aes(x = xval, y = ..y..), fun = dbeta,   
  colour="orchid", n = length(z$Freq), args =
  list(shape1=shape1ML,shape2=shape2ML))

pSpecial + statSpecial
```

## normal distribution fit the data the best
## new normal distribution
```{r}

r <- rnorm(100,262,0.4670539)
df_r <- as.data.frame(r)
p7 <- ggplot(data=df_r, aes(x=r, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2)

p7

```

